### ISSUE TITLE
Giiker Filter Restriction 

### ISSUE THREAD

**Issue by isaacrbeam** [cubing/cuble.js#20]
Good Afternoon,

I would first like to say that this project is absolutely awesome and wanted to inform the team of the current pairing prefix restriction. As new cubes are released, the cube namePrefix may change. I discovered this to be the case as I was able to connect my cube to the production https://bluetooth.cubing.net site and not on a local host copy. After digging into the source code of the live site, I discovered the issue to the namePrefix. 

Project Source Code:
`
  filters: [
    {namePrefix: "GiC"},
    {namePrefix: "GiS"},
    {namePrefix: "GiY"}
  ],`
Production Source Code:
`  filters: [{
        namePrefix: "Gi"
      }],`

Just wanted to let the the team and new developers know in case they run into the same issue.

**Comment by lgarron** [comment]
https://bluetooth.cubing.net supports all known GiiKER models, Gan 356i, and GoCube now!
